### ISSUE TITLE
Commands and other non-core functionality should be in a different repo

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis_2.0#11]
It would be better for organisation, customization and being a good development practice.

Now that this repo doesn't have any non-core functionality yet, I think we should make a different repo for all the non-core functionality.

**Comment by Sceleratis** [comment]
> It would be better for organisation, customization and being a good development practice.
> 
> Now that this repo doesn't have any non-core functionality yet, I think we should make a different repo for all the non-core functionality.

My plan was for this repo to be the entirety of whatever ships with 2.0 by default, including all commands. I was going to have a core branch for just the core functionality.

**Comment by ccuser44** [comment]
> > It would be better for organisation, customization and being a good development practice.
> Now that this repo doesn't have any non-core functionality yet, I think we should make a different repo for all the non-core functionality.
>
> My plan was for this repo to be the entirety of whatever ships with 2.0 by default, including all commands. I was going to have a core branch for just the core functionality which has everything not-core related stripped.
> 
> I definitely don't want to put it in a different repo entirely as then cherry picking changes becomes more annoying, plus it would make more sense as just a branch.

I understand why you don't wan't to do this however by doing so we would avoid a lot of unnecessary features which are baked in to the core, but only make sense because of a niehe command. By doing this we would keep the core clean.
I propose that the non-core features are at least installed via a package rather than baked in to the core.

**Comment by Sceleratis** [comment]
> > > It would be better for organisation, customization and being a good development practice.
> > > Now that this repo doesn't have any non-core functionality yet, I think we should make a different repo for all the non-core functionality.
> > 
> > 
> > My plan was for this repo to be the entirety of whatever ships with 2.0 by default, including all commands. I was going to have a core branch for just the core functionality which has everything not-core related stripped.
> > I definitely don't want to put it in a different repo entirely as then cherry picking changes becomes more annoying, plus it would make more sense as just a branch.
> 
> I understand why you don't wan't to do this however by doing so we would avoid a lot of unnecessary features which are baked in to the core, but only make sense because of a niehe command. By doing this we would keep the core clean. I propose that the non-core features are at least installed via a package rather than baked in to the core.

Features that are considered non-core are not being included in the Core package, instead they get included in whatever package it is that's providing stuff that needs those features. Removing non-core functionality is going to be as simple as just not including non-core packages (like the ones responsible for commands, UI, and whatever else.) Because of how packages work there shouldn't be any issues with just excluding unimportant ones from the Core branch.

**Comment by ccuser44** [comment]
> > > > It would be better for organisation, customization and being a good development practice.
> > > > Now that this repo doesn't have any non-core functionality yet, I think we should make a different repo for all the non-core functionality.
>
> > > My plan was for this repo to be the entirety of whatever ships with 2.0 by default, including all commands. I was going to have a core branch for just the core functionality which has everything not-core related stripped.
>
> > I definitely don't want to put it in a different repo entirely as then cherry picking changes becomes more annoying, plus it would make more sense as just a branch.
> > I understand why you don't wan't to do this however by doing so we would avoid a lot of unnecessary features which are baked in to the core, but only make sense because of a niehe command. By doing this we would keep the core clean. I propose that the non-core features are at least installed via a package rather than baked in to the core.
> 
> Features that are considered non-core are not being included in the Core package, instead they get included in whatever package it is that's providing stuff that needs those features. Removing non-core functionality is going to be as simple as just not including non-core packages (like the ones responsible for commands, UI, and whatever else.) Because of how packages work there shouldn't be any issues with just excluding unimportant ones from the Core branch. Technically one could just remove packages in reversed order of importance and as long as there isn't a dependency issue it should be fine.... can also just remove all of them, or all of them except for System.Utilities and System.Core (the real "Core" packages most things needs.)

Yeah maybe the different repo thing doesn't make much sense. But I still think the core and the non-core stuff should be in different repos (and be developed at least somewhat seperately) to avoid certain design issues that were made in 1.0

**Comment by Sceleratis** [comment]
> > > > > It would be better for organisation, customization and being a good development practice.
> > > > > Now that this repo doesn't have any non-core functionality yet, I think we should make a different repo for all the non-core functionality.
> > 
> > 
> > > > My plan was for this repo to be the entirety of whatever ships with 2.0 by default, including all commands. I was going to have a core branch for just the core functionality which has everything not-core related stripped.
> > 
> > 
> > > I definitely don't want to put it in a different repo entirely as then cherry picking changes becomes more annoying, plus it would make more sense as just a branch.
> > > I understand why you don't wan't to do this however by doing so we would avoid a lot of unnecessary features which are baked in to the core, but only make sense because of a niehe command. By doing this we would keep the core clean. I propose that the non-core features are at least installed via a package rather than baked in to the core.
> > 
> > 
> > Features that are considered non-core are not being included in the Core package, instead they get included in whatever package it is that's providing stuff that needs those features. Removing non-core functionality is going to be as simple as just not including non-core packages (like the ones responsible for commands, UI, and whatever else.) Because of how packages work there shouldn't be any issues with just excluding unimportant ones from the Core branch. Technically one could just remove packages in reversed order of importance and as long as there isn't a dependency issue it should be fine.... can also just remove all of them, or all of them except for System.Utilities and System.Core (the real "Core" packages most things needs.)
> 
> Yeah maybe the different repo thing doesn't make much sense. But I still think the core and the non-core stuff should be in different repos (and be developed at least somewhat seperately) to avoid certain design issues that were made in 1.0

I don't think there's reason to separate the repos tho as that only makes it more difficult to keep both of them up to date when there's changes to the core. A different branch would be sufficient wouldn't it?

**Comment by ccuser44** [comment]
> 
> I don't think there's reason to separate the repos tho as that only makes it more difficult to keep both of them up to date when there's changes to the core. A different branch would be sufficient wouldn't it?

Yeah I think the different branch thing is good

**Comment by joritochip** [comment]
> > 
> > I don't think there's reason to separate the repos tho as that only makes it more difficult to keep both of them up to date when there's changes to the core. A different branch would be sufficient wouldn't it?
> 
> Yeah I think the different branch thing is good

That isn't really what branches are meant to be used for... GitHub especially seems to imply that branches should be used for different versions of the same code rather than separate code entirely.

I don't see the problem having the packages that ship by default being in the same branch in the same repo. Monorepos are a pretty common practice when you have multiple, separate "packages" like us.

**Comment by ccuser44** [comment]
> > > I don't think there's reason to separate the repos tho as that only makes it more difficult to keep both of them up to date when there's changes to the core. A different branch would be sufficient wouldn't it?
> 
> > Yeah I think the different branch thing is good
> 
> That isn't really what branches are meant to be used for... GitHub especially seems to imply that branches should be used for different versions of the same code rather than separate code entirely.
> 
> I don't see the problem having the packages that ship by default being in the same branch in the same repo. Monorepos are a pretty common practice when you have multiple, separate "packages" like us.


Having the core code mixed up with production code can lead to bad develooment practices. Like for example some obscure feature may lead to a mostly unnecessary addition be added to the core code. This has happened in 1.0 many tines.

Another issue is that it may be hard to seperate the non-core cpde from the core code.
