### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by SxolarTK** [Sceleratis/Adonis_2.0#15]
Yeah uh so, I have chatlocalization that allows it so when you join the chat it shows chat instantly but now it does not do that. I'm not sure if it has to go with adonis admin or just something else.

**Comment by joritochip** [comment]
What do you mean "shows chat instantly but now it does not"?? Also, this repository is for Adonis 2.0, which is still heavily in development and shouldn't be used in games yet.

**Comment by SxolarTK** [comment]
What do you mean "shows chat instantly but now it does not"?? Also, this repository is for Adonis 2.0, which is still heavily in development and shouldn't be used in games yet.
Example: Let's say you had a custom bubble chat and it immediately gives you the chat, but now, it does not show when you reset or join the game.
