### ISSUE TITLE
Instead of getfenv or setfenv we should use a virtual fenv instead

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis_2.0#3]
Instead of getfenv or setfenv we should use a virtual fenv instead. So we would keep the  luau optimisations.

Also we rely on loadstring the least we possibly can as it introduces potential security issues.

I mean only in the LBI, we shoudnlt use an ENV anywhere else for obvoius reasons.

**Comment by Sceleratis** [comment]
I plan to mostly avoid loadstring-related stuff as much as possible but felt the functionality was at least work including. As to the virtual env I agree, just that would mean creating a fat table somewhere with all of the various roblox globals, so in the meantime I opted to just use getfenv.

**Comment by ccuser44** [comment]
> I plan to mostly avoid loadstring-related stuff as much as possible but felt the functionality was at least worth including.

Yeah I thunk we should be avoiding it in 2.0. it should only exist for the :script command purpose, there also should be a way to make it disabled hardcoded due to several security issues.

**Comment by Sceleratis** [comment]
> > I plan to mostly avoid loadstring-related stuff as much as possible but felt the functionality was at least worth including.
> 
> Yeah I think we should be avoiding it in 2.0. It should only exist for the :script command purpose, there also should be a way to make it disabled hardcoded due to several security issues.

tbh probably won't even be needed for :script
