### ISSUE TITLE
Adonis not working in some servers

### ISSUE THREAD

**Issue by bruninho1337** [Sceleratis/Adonis_2.0#36]
I'm having a glitch that Adonis doesn't works in some of servers of my game

It says this error (After Adonis Loading Complete): 

![image](https://github.com/Epix-Incorporated/Adonis_2.0/assets/111817596/9f411274-df63-4a8a-ae0a-d8b676602a30)

This just happens in some servers of my game

**Comment by NoobBucket** [comment]
Adonis 2.0 is still in early development and not stable for use. Is there a particular reason you're using 2.0?

**Comment by NoobBucket** [comment]
here: https://www.roblox.com/library/7510622625/Adonis-Admin-Loader-Epix-Incorporated

**Comment by NoobBucket** [comment]
adonis 2.0 is an experimental in development version that is not production ready. so are you using the original adonis or this in-dev version?

**Comment by Dimenpsyonal** [comment]
Then you're on the wrong repository. Report this on https://github.com/Epix-Incorporated/Adonis
